# Generated by Django 2.1.3 on 2018-12-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='category_drone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='category_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='category_sos',
            field=models.BooleanField(default=False),
        ),
    ]
