# Generated by Django 2.1.5 on 2019-01-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(null=True, upload_to='documents'),
        ),
    ]
