# Generated by Django 2.1.3 on 2018-12-25 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181226_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category_all',
            new_name='all_categories',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category_drone',
            new_name='drone',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category_management',
            new_name='management',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category_sos',
            new_name='sos',
        ),
    ]
