# Generated by Django 2.1.5 on 2019-01-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190130_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
