# Generated by Django 2.1.3 on 2018-12-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181226_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='all_categories',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='drone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='sos',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Management',
        ),
    ]
