# Generated by Django 2.1.3 on 2018-12-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181226_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='all_categories',
        ),
        migrations.RemoveField(
            model_name='post',
            name='drone',
        ),
        migrations.RemoveField(
            model_name='post',
            name='management',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sos',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('All', 'Drone'), ('Management', 'Sos')], default='all', max_length=100),
        ),
    ]
