# Generated by Django 2.1.3 on 2018-12-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181226_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('All', 'All'), ('Drone', 'Drone'), ('Management', 'Management'), ('SOS', 'SOS')], default='all', max_length=100),
        ),
    ]
