# Generated by Django 2.1.4 on 2018-12-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181226_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(default='documents/something.jpg', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('all', 'all'), ('drone', 'drone'), ('management', 'management'), ('sos', 'sos')], default='all', max_length=100),
        ),
    ]
