# Generated by Django 2.1.4 on 2018-12-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181226_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='files',
        ),
        migrations.AddField(
            model_name='post',
            name='filess',
            field=models.FileField(default='something.jpg', upload_to='documents'),
        ),
    ]
