# Generated by Django 2.1.4 on 2018-12-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20181226_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='filess',
            new_name='files',
        ),
    ]
