# Generated by Django 2.1.4 on 2018-12-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20181226_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='files',
        ),
    ]
