# Generated by Django 2.1.3 on 2019-01-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_post_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_field',
            field=models.FileField(null=True, upload_to='documents'),
        ),
    ]
