# Generated by Django 2.1.5 on 2019-01-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_file_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file_field',
        ),
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
