# Generated by Django 2.1.5 on 2019-01-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190128_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='all', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(default='udahgoighao', upload_to=''),
        ),
    ]
