# Generated by Django 2.1.5 on 2019-01-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190128_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(upload_to=''),
        ),
    ]
