# Generated by Django 2.1.5 on 2019-01-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20190129_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(blank=True, choices=[('all', 'all'), ('drone', 'Drone'), ('management', 'Management'), ('SOS', 'SOS')], max_length=30, null=True),
        ),
    ]
