# Generated by Django 2.1.5 on 2019-01-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20190129_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('all', 'all'), ('drone', 'Drone'), ('management', 'Management'), ('SOS', 'SOS')], max_length=30),
        ),
    ]
