# Generated by Django 2.1.5 on 2019-01-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20190129_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
